In [5]:
import torch

d = [[1, 2], [3,4]]
x = torch.tensor(d)
print(x)
t = x
t[:,1] = 0
print(t)
y1 = t @ t.T
y2 = t.matmul(t.T)

print(y1)
print(y2)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])
